name: Publish Docker Images

on:
  push:
  pull_request:
    types: [labeled, closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true

    steps:
      - name: echo a thing or two
        run: echo $(jq -r '.label.name' $GITHUB_EVENT_PATH)
        
      - name: Check if PR is labeled as "publish docker"
        id: check_label 
        run: echo "publish docker=$(jq -r '.label.name' $GITHUB_EVENT_PATH | grep -c '^publish docker$')" >> $GITHUB_ENV

      - name: Execute Script
        if: steps.check_label.outputs.publish == '1'
        run: |
          ./your-script.sh
